// src/themes/index.ts
// Theme registry — the active theme is driven by /config/theme/active.ts.
// That file is generated from skeleton.config.json — never edit it directly.
// Custom theme token overrides can be registered here.
//
// Do not edit this file manually unless you are extending beyond what the
// agent writes into /config/theme/active.ts.

export const THEMES: Record<string, unknown> = {};
